service: mix-lists
org: cmgcode

provider:
  name: aws
  runtime: java8
  stage: dev
  region: ap-southeast-2
  memorySize: 1472

package:
  artifact: build/libs/mix-lists-dev-all.jar

plugins:
  - serverless-finch

custom:
  client:
    bucketName: mix-lists-view

functions:
  checklists:
    handler: com.cmgcode.api.ChecklistEndpoint
    events:
      - http:
          path: checklists
          method: get
          cors: true
  merge:
    handler: com.cmgcode.api.MergeEndpoint
    events:
      - http:
          path: merge
          method: post
          cors: true