service: mix-lists
org: cmgcode

provider:
  name: aws
  runtime: java8
  stage: dev
  region: ap-southeast-2
  memorySize: 1472

package:
  artifact: build/libs/mix-lists-dev-all.jar

functions:
  mix-lists:
    handler: com.cmgcode.api.Checklist
    events:
      - http:
          path: checklists
          method: get
          cors: true